name: Build Mouse App
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        pip install pyinstaller opencv-python mediapipe pyautogui numpy
    - name: Build with PyInstaller
      run: pyinstaller --onefile --noconsole gesture_mouse.py
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: gesture-mouse-app
        path: dist/gesture_mouse.exe
